workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-signing
      vars:
        PACKAGE_NAME: "com.aistudio.batterytracker.qwerty"
      node: latest
    scripts:
      - name: Set up Environment and local.properties
        script: |
          # إنشاء ملف البيئة الفارغ
          touch .env.example
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
          # توليد ملف debug.keystore تلقائياً لحل مشكلة التوقيع الرقمي
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      - name: Upgrade Gradle Wrapper and Build
        script: |
          gradle wrapper --gradle-version 9.3.1
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@gmail.com
        notify:
          success: true
          failure: true
