workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-signing
      vars:
        PACKAGE_NAME: "com.aistudio.batterytracker.qwerty"
      node: latest
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Upgrade Gradle Wrapper and Build
        script: |
          # هذا السطر يقوم بتحديث الجرادل تلقائياً للإصدار المطلوب لحل مشكلة التوافق
          gradle wrapper --gradle-version 9.3.1
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@gmail.com
        notify:
          success: true
          failure: true
